@startuml Test
left to right direction

actor Utilisateur as u

package Admin {
actor CEO as ceo
actor CTO as cto 
}

ceo --> u
package SiteVitrine {
  usecase "Visiter les projets" as UC2
  usecase "Projets Back" as UC5
  usecase "Projets Front" as UC6
}

  usecase "Infos de contact" as UC4

package backOffice{
  usecase "Rediger ses projets" as UC1
  usecase "Afficher le nom de la techno" as UC3
}
ceo --> UC1 
UC1 --> UC2
u --> UC2
u --> UC4
UC2 --> UC5
UC2 --> UC6
UC3 --> UC1
cto --> UC3 
@enduml